# Essentials
# ------------------------------------------------
# https://www.mkdocs.org
# https://squidfunk.github.io/mkdocs-material

site_name: OpenAD
docs_dir: main
repo_url: https://github.com/acceleratedscience/openad-toolkit
nav:
    # - Style Reference: style-reference.md
    - Home: index.md
    - Documentation:
          - Installation: _docs/installation.md
          - Tell Me: _docs/tell-me.md
          - Commands: _docs/commands.md
          - Developers: _docs/developers.md
          - Getting Started: _docs/getting-started.md
          - Plugins: _docs/plugins.md
          - Model Service:
              - Model Service: _docs/model-service/model-service.md
              - Hosting Your Own: _docs/model-service/hosting-your-own.md
              - IBM Hosted: _docs/model-service/ibm-hosted.md
              - Wrapping Models: _docs/model-service/wrapping.md
    - Tutorials:
          - _blog/category/tutorials/
    - Blog:
          - _blog/index.md
    - About: about.md
    # - Category:
    #       - Topic A: example/topic-a.md
    #       - Topic B: example/topic-b.md
    #       - Sub Theme:
    #             - Topic C: example/sub-category/topic-c.md

# Theme configuration
# ------------------------------------------------
# https://squidfunk.github.io/mkdocs-material/setup

theme:
    name: material
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: carbon/icn-dark-mode-auto
              name: Dark mode auto

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: carbon
          toggle:
              icon: carbon/icn-dark-mode-off
              name: Dark mode on

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: carbon-dark
          toggle:
              icon: carbon/icn-dark-mode-on
              name: Dark mode off

    # Replace icons
    logo: assets_main/icn-logo.svg
    # favicon: assets_main/icn-logo.svg
    favicon: assets_main/icn-bee.svg
    icon:
        menu: carbon/icn-hamburger
        alternate: carbon/icn-language
        search: carbon/icn-search
        share: carbon/icn-share
        close: carbon/icn-close
        top: carbon/icn-arrow-up
        edit: carbon/icn-edit
        view: carbon/icn-file-html
        repo: carbon/icn-github
        previous: carbon/icn-arrow-left
        next: carbon/icn-arrow-right
        # tag: carbon/icn-star - https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#tag-icons-and-identifiers
        admonition:
            note: carbon/icn-megaphone
            abstract: carbon/icn-result
            info: carbon/icn-info
            tip: carbon/icn-fire
            success: carbon/icn-yes
            question: carbon/icn-question
            warning: carbon/icn-warning
            failure: carbon/icn-no
            danger: carbon/icn-caution
            bug: carbon/icn-bug
            example: carbon/icn-person
            quote: carbon/icn-quote

    features:
        - navigation.tabs # Tabs for main sections
        # - navigation.instant # Navigate without reloading the page
        # - navigation.instant.progress # Progress bar
        - navigation.top # Back to top link
        # - navigation.path # Breadcrumbs - sponsors only
        - toc.follow # Auto-scroll the TOC sidebar
        - content.code.copy
        - content.code.annotate
        # - content.code.select # Auto-select - sponsors only
        # - content.tooltips # HTML tooltips, rather annoying since you can't disable them on headers etc.
    
    # Overrides let us specify different HTML files
    # for certain pages, used to customize the landing
    # as well as custom icons
    custom_dir: main/overrides

extra_css:
    - css/carbon-vars.css
    - css/carbon-color-palette.css
    - css/carbon-base.css
    - css/carbon-page-header.css
    - css/carbon-nav.css
    - css/carbon-side-nav.css
    - css/carbon-layout.css
    - css/carbon-blog.css
    - css/carbon-blog-meta.css
    - css/carbon-admonitions.css
    - css/main.css

plugins:
    - search
  
    # Enable blog
    - blog:
          blog_dir: _blog
          post_date_format: medium
          post_excerpt: required
    
    # Created nice cars for social media
    # Can't get iage processing to work, abandoned for now
    # https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/
    # - social

# See file for details
# hooks:
#     - custom_hooks.py

# Enable page status
extra:
    status:
        new: new content

# Extensions
# ------------------------------------------------

markdown_extensions:
    # Turns every header into a link
    - toc:
          permalink: ยง

    # Allow setting attributes on elements
    # eg. [link](url){data-preview}
    - attr_list

    # Lets us wrap markdown in HTML tags
    - md_in_html

    # Allows for image captions
    - pymdownx.blocks.caption

    # Icons
    # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - main/overrides/.icons

    # Code formatting
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
          auto_title: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    # Warning / note etc.
    - admonition

    # Instant preview of links
    # Nice to have feature, but only available to sponsors
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=data+preview#instant-previews
    # - material.extensions.preview:
    #     configurations:
    #       - targets:
    #           include:
    #             - changelog/index.md
