# Note: we hide teh avatar and description, but
# these fields are required by the blog plugin.
authors:
    moenen:
        name: Moenen Erbuer
        description: x
        avatar: https://avatars.githubusercontent.com/u/122490537
    phil:
        name: Phil Downey
        description: x
        avatar: https://avatars.githubusercontent.com/u/122490537
